/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model({ onAnimationsLoaded, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Artemis SLS alpha.glb')
  const { actions, names } = useAnimations(animations, group)

  // Pass animation data to parent component
  React.useEffect(() => {
    if (onAnimationsLoaded && actions && names) {
      onAnimationsLoaded({ actions, names })
    }
  }, [actions, names, onAnimationsLoaded])
  
    return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="artemis_root">
          <group name="artemis_booster_1" position={[6.4, 0, -30.12]}>
            <mesh
              name="L_SolBooster"
              castShadow
              receiveShadow
              geometry={nodes.L_SolBooster.geometry}
              material={materials.m_Artemis}
              position={[0, 0, -6.508]}
            />
          </group>
          <group name="artemis_booster_2" position={[-6.4, 0, -30.12]}>
            <mesh
              name="R_SolBooster"
              castShadow
              receiveShadow
              geometry={nodes.R_SolBooster.geometry}
              material={materials.m_Artemis}
              position={[0, 0, -6.508]}
              rotation={[0, 0, -Math.PI]}
            />
          </group>
          <group name="artemis_core">
            <mesh
              name="CoreStage"
              castShadow
              receiveShadow
              geometry={nodes.CoreStage.geometry}
              material={materials.m_Artemis}
              position={[0, 0, -36.628]}
            />
          </group>
          <group name="artemis_fairings" position={[0, 0, 44.134]}>
            <group name="fairing" position={[0, -2.955, -0.39]} rotation={[0, 0, Math.PI]}>
              <mesh
                name="Fairings"
                castShadow
                receiveShadow
                geometry={nodes.Fairings.geometry}
                material={materials.m_Artemis}
                position={[0, -2.955, 0]}
                rotation={[0, 0, -Math.PI]}
              />
            </group>
            <group name="fairing001" position={[-2.42, 1.695, -0.39]} rotation={[0, 0, 0.96]}>
              <mesh
                name="Fairings001"
                castShadow
                receiveShadow
                geometry={nodes.Fairings001.geometry}
                material={materials.m_Artemis}
                position={[0, -2.955, 0]}
                rotation={[0, 0, -0.96]}
              />
            </group>
            <group name="fairing002" position={[2.42, 1.695, -0.39]} rotation={[0, 0, -0.96]}>
              <mesh
                name="Fairings002"
                castShadow
                receiveShadow
                geometry={nodes.Fairings002.geometry}
                material={materials.m_Artemis}
                position={[0, -2.955, 0]}
                rotation={[0, 0, 0.96]}
              />
            </group>
          </group>
          <group name="artemis_LAS" position={[0, 0, 50.405]}>
            <mesh
              name="LAS"
              castShadow
              receiveShadow
              geometry={nodes.LAS.geometry}
              material={materials.m_Artemis}
              position={[0, 0, -4.389]}
            />
          </group>
          <group name="Orion_Master" position={[0, 0, 42.635]}>
            <group name="ICSP" position={[0, 0, -3.469]}>
              <mesh
                name="ICPS"
                castShadow
                receiveShadow
                geometry={nodes.ICPS.geometry}
                material={materials.m_Artemis}
                position={[0, 0, -2.736]}
              />
            </group>
            <group name="Orion_group" position={[0, 0, 3.647]}>
              <group name="orion_capsule" position={[0, 0, 1.23]}>
                <mesh
                  name="Orion_Capsule"
                  castShadow
                  receiveShadow
                  geometry={nodes.Orion_Capsule.geometry}
                  material={materials.m_Artemis}
                  position={[0, 0, -0.606]}
                />
              </group>
              <group name="orion_module" position={[0, 0, -0.899]}>
                <group name="orion_armature" position={[0, 0, -1.188]}>
                  <skinnedMesh
                    name="OrionModule"
                    geometry={nodes.OrionModule.geometry}
                    material={materials.m_Artemis}
                    skeleton={nodes.OrionModule.skeleton}
                  />
                  <primitive object={nodes.root} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Artemis SLS alpha.glb')
